export const nigerianStates = [
    { id: 1, name: "Abia" },
    { id: 2, name: "Adamawa" },
    { id: 3, name: "Akwa Ibom" },
    { id: 4, name: "Anambra" },
    { id: 5, name: "Bauchi" },
    { id: 6, name: "Bayelsa" },
    { id: 7, name: "Benue" },
    { id: 8, name: "Borno" },
    { id: 9, name: "Cross River" },
    { id: 10, name: "Delta" },
    { id: 11, name: "Ebonyi" },
    { id: 12, name: "Edo" },
    { id: 13, name: "Ekiti" },
    { id: 14, name: "Enugu" },
    { id: 15, name: "Gombe" },
    { id: 16, name: "Imo" },
    { id: 17, name: "Jigawa" },
    { id: 18, name: "Kaduna" },
    { id: 19, name: "Kano" },
    { id: 20, name: "Kogi" },
    { id: 21, name: "Kwara" },
    { id: 22, name: "Lagos" },
    { id: 23, name: "Nasarawa" },
    { id: 24, name: "Niger" },
    { id: 25, name: "Ogun" },
    { id: 26, name: "Ondo" },
    { id: 27, name: "Osun" },
    { id: 28, name: "Oyo" },
    { id: 29, name: "Plateau" },
    { id: 30, name: "Rivers" },
    { id: 31, name: "Sokoto" },
    { id: 32, name: "Taraba" },
    { id: 33, name: "Yobe" },
    { id: 34, name: "Zamfara" },
    { id: 35, name: "FCT" },
  ];